require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  bookingsync-rubocop:
    - config/base.yml
    - config/rails.yml
    - config/rspec.yml

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - gemfiles/*

Lint/RedundantRequireStatement:
  Exclude:
    - 'lib/operations.rb'
