name: CI
on: [push]
jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { ruby: '2.7', rails: '5.2' }
          - { ruby: '2.7', rails: '6.0' }
          - { ruby: '3.0', rails: '6.1' }
          - { ruby: '3.1', rails: '7.0' }
          - { ruby: '3.2', rails: '7.1' }
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails.${{ matrix.rails }}.gemfile
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: bundle exec rubocop
